general:
  port: 8080

metrics:
  port: 9090

database:
  path: "database.db"

tracker:
  url: https://your-domain.atlassian.net/rest/api/3/issue
  token: your-jira-api-token

ticket:
  project:
    key: SUPPORT
  issuetype:
    name: Task
  labels:
    - API
    - Critical
  priority:
    name: High
